Flask Web开发实战/bluelog/bluelog/blueprints/blog.py
# -*- coding: utf-8 -*-

from flask import render_template, Blueprint

blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/')
def index():
    return render_template('blog/index.html')


@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')


@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    return render_template('blog/category.html')


@blog_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    return render_template('blog/post.html')

Flask Web开发实战/bluelog/bluelog/templates/blog/_posts.html
{% if posts %}
{% for post in posts %}
<h3 class="text-primary">
    <a href="{{ url_for('.show_post', post_id=post.id ) }}">
        {{ post.title }}
    </a>
</h3>
<p>
    {{ post.body|striptags|truncate }}
    <small>
        <a href="{{ url_for('.show_post', post_id=post.id) }}">Read More</a>
    </small>
</p>
<small>
    Comments: <a href="{{ url_for('.show_post', post_id=post.id ) }}#comments">{{ post.comments|length }}</a>
    Category: <a href="{{ url_for('.show_category', category_id=post.category_id }}">{{ post.category.name }}</a>
    <span class="float-right">
        {{ moment(post.timestamp).format('LL') }}
    </span>
</small>
{% if not loop.last %}
<hr>
{% endif %}
{% endfor %}
{% else %}
<div class="tip">
    <h5>No posts yet.</h5>
</div>
{% endif %}

Flask Web开发实战/bluelog/bluelog/templates/blog/_sidebar.html
{% if links %}
<div class="card mb-3">
    <div class="card-header">Links</div>
    <ul class="list-group list-group-flush">
        {% for link in links %}
        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
            <a href="{{ link.url }}" target="_blank">{{ link.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

{% if categories %}
<div class="card mb-3">
    <div class="card-header">Categories</div>
    <ul class="list-group list-group-flush">
        {% for category in categories %}
        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
            <a href="{{ url_for('blog.show_category', category_id=category.id )}}">
                {{ category.name }}
            </a>
            <span class="badge badge-primary badge-pill">
                {{ category.posts|length }}
            </span>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

Flask Web开发实战/bluelog/bluelog/templates/blog/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<div class="page-header">
    <h1>About</h1>
</div>
<div class="row">
    <div class="col-sm-8">
        {{ admin.about|about }}
    </div>
    <div class="col-sm-4 sidebar">
        {% include "blog/_sidebar.html" %}
    </div>
</div>
{% endblock %}

Flask Web开发实战/bluelog/bluelog/templates/blog/index.html
{% extends 'base.html' %}

<!-- {% from 'bootstrap/pagination.html' import render_pager %} -->
{% from 'bootstrap/pagination.html' import render_pager %}
{% block title %} Home {%  endblock %}

{% block content %}
<div class="page-header">
    <h1 class="display-3">{{ admin.blog_title|default('Blog Title') }}</h1>
    <h4 class="text-muted">&nbsp;{{ admin.blog_sub_title|default('Blog Subtitle') }}</h1>
</div>
<div class="row">
    <div class="col-sm-8"></div>
    <div class="col-sm-4 sidebar">
        {% include 'blog/_sidebar.html' %}
    </div>
</div>
{% endblock %}